#LOGGING
RUN_TITLE : 'QED+SYNTH_rawtrain'

ACTOR_RESTART_PATH :  None #[DOCK_RESET/ckpt_5/actor_checkpoint,DOCK_RESET/config.yaml]  #QED_WEIGHT13_400000 #'../MODELS/SmallModel2/'
CRITIC_RESTART_PATH : None #[DOCK_RESET/ckpt_5/critic_checkpoint, DOCK_RESET/config.yaml]
# RESTART_PATH : 'None'
# #ENVIROMENT VARIABLES
ENVIROMENT_VARIABLES:
  NUM_NODE_FEATS : 54
  MOL_FEATURIZER : 'mol_to_graph_full'
  REWARD_MODULES : [QED, SYNTH]
  
MODEL_VARIABLES : 
  HIDDEN_DIM : 450
  NUM_ATOM_TYPES : 17

ACTOR_VARIABLES :
  HIDDEN_DIM: 450

  NUM_ATOM_TYPES:  17
  DROPOUT: .85
  GRAPH_ACTIVATION: 'LeakyReLU'
  DENSE_ACTIVATION: 'LeakyReLU'
  MODEL_TYPE:  GatedGraphConv
  GRAPH_NUM_LAYERS: 3
  DENSE_NUM_LAYERS: 2
  DENSE_NORMALIZATION: 'SpectralNorm'

CRITIC_VARIABLES :
  HIDDEN_DIM: 500

  NUM_ATOM_TYPES:  17
  DROPOUT: 0
  GRAPH_ACTIVATION: 'ReLU'
  DENSE_ACTIVATION: 'ReLU'
  MODEL_TYPE:  GatedGraphConv
  GRAPH_NUM_LAYERS: 3
  DENSE_NUM_LAYERS: 4
  DENSE_NORMALIZATION: 'None'

PPO_VARIABLES :
  PPO_BATCH_SIZE : 256
  TIMESTEPS_PER_ITERATION : 3000
  CLIP : 0.1
  A_LR : 1e-4
  C_LR : 3e-4
  NUM_UPDATED_PER_ITERATION : 6
  MAX_TIMESTEPS_PER_EPISODE : 30
  GAMMA : .99



#SUPERVISED TRAINING VARIABLES
SUPERVISED_TRAINING_VARIABLES:
  LR : 0.00028
  DECAY : 0.916
  SUPERVISED_BATCH_SIZE : 256
  DATASET_SIZE : 507528
  PATH : '../GraphDecomp/graph_decomp/graphs'

FINAL_TRAINING_VARIABLES:
  SV_EPOCHS : 0
  PPO_STEPS : 400000
